vino-house:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: VinoHouse_take_out
    username: root
    password: xxy123.
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t**********  # 敏感信息
    access-key-secret: h0sUty**********  # 敏感信息
    bucket-name: vino-house
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10  # 一共 16 个，默认 0
  wechat:
    appid: wx1561e3829392b939
    secret: 1ce5c30c4b349572432e551be53411ba