server:
  port: 8080

spring:
  profiles:
    active: dev  # 设置环境
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${vino-house.datasource.driver-class-name}
      url: jdbc:mysql://${vino-house.datasource.host}:${vino-house.datasource.port}/${vino-house.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${vino-house.datasource.username}
      password: ${vino-house.datasource.password}
  redis:
    host: ${vino-house.redis.host}
    port: ${vino-house.redis.port}
    password: ${vino-house.redis.password}
    database: ${vino-house.redis.database}

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.VinoHouse.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      VinoHouse:
        mapper: debug
        service: info
        controller: info

vino-house: # 与 JwtProperties 中的 @ConfigurationProperties 保持一致
  jwt:
    admin-secret-key: zms  # 设置 jwt 签名加密时使用的秘钥
    admin-ttl: 7200000  # 设置 jwt 过期时间：2h
    admin-token-name: token  # 设置前端传递过来的令牌名称
    user-secret-key: aq
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${vino-house.alioss.endpoint}
    access-key-id: ${vino-house.alioss.access-key-id}
    access-key-secret: ${vino-house.alioss.access-key-secret}
    bucket-name: ${vino-house.alioss.bucket-name}
  wechat:
    appid: ${vino-house.wechat.appid}  # 微信小程序 appid
    secret: ${vino-house.wechat.secret}  # 微信小程序密钥
    mchid: ${vino-house.wechat.mchid}  # 微信商户号
    mchSerialNo: ${vino-house.wechat.mchSerialNo}  # 商户 API 证书序列号
    privateKeyFilePath: ${vino-house.wechat.privateKeyFilePath}  # 商户私钥文件路径
    apiV3Key: ${vino-house.wechat.apiV3Key}  # 证书解密密钥
    weChatPayCertFilePath: ${vino-house.wechat.weChatPayCertFilePath}  # 证书文件路径
    notifyUrl: ${vino-house.wechat.notifyUrl}  # 支付成功回调地址
    refundNotifyUrl: ${vino-house.wechat.refundNotifyUrl}  # 退款成功回调地址
  shop:
    address: 上海市浦东新区陆家嘴
  baidu:
    ak: 1hybSH6Z56KGXXvbuIazkPXN5aNxY8rS