vino-house:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: VinoHouse_take_out
    username: root
    password: xxy123.
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t**********  # 敏感信息
    access-key-secret: h0sUty**********  # 敏感信息
    bucket-name: vino-house
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10